/**
 * Real SWU Forge exports for local testing. They hold real player handles and ids, so they live OUTSIDE the
 * repo (the forks are public) and are only read at test time; tests that need them skip when they are absent.
 *
 *   REPLAY_FIXTURES_DIR (default: the overseer hub's forge-fortify-fix/real folder)
 *     verdant-3f844c65.json            the Verdant Fortress game, saved from the Wicket seat (double-sided)
 *     verdant-3f844c65-opponent.json   the same game, saved from the Boba Fett seat
 *     tarkin-5adf3f43.json, memorial-55123051.json   single-sided replays (refusal path)
 */
import fs from 'node:fs';
import path from 'node:path';
import { parseForgeRecording } from '../../../src/app/sandbox/_lib/replay/forgeExport';
import { IReplayGame, pairRecordings } from '../../../src/app/sandbox/_lib/replay/replayGame';
import { NormalizedCard } from '../../../src/app/sandbox/_lib/replay/forgeTimeline';
import { IReplayCards, replayCardsFrom } from '../../../src/app/sandbox/_lib/replay/replayCards';
import type { ISandboxCard } from '../../../src/app/sandbox/_lib/cardIndex';

export const REPLAY_DIR = process.env.REPLAY_FIXTURES_DIR
    ?? '/Users/parker/code/overseer-hub/.claude/orchestrator/streams/forge-fortify-fix/real';

export const realReplayPath = (name: string) => path.join(REPLAY_DIR, name);
export const hasRealReplay = (...names: string[]) => names.every((n) => fs.existsSync(realReplayPath(n)));
export const readRealReplay = (name: string) => fs.readFileSync(realReplayPath(name), 'utf8');

export const VERDANT = ['verdant-3f844c65.json', 'verdant-3f844c65-opponent.json'];

export const loadVerdantGame = (): IReplayGame => {
    const [a, b] = VERDANT.map((n) => parseForgeRecording(readRealReplay(n)));
    if (!a.ok || !b.ok) {
        throw new Error('could not read the Verdant pair');
    }
    const paired = pairRecordings(a.recording, b.recording);
    if (!paired.ok) {
        throw new Error(paired.error);
    }
    return paired.game;
};

/** The engine's filler card (Underworld Thug, SHD 257): it never appears in these games. */
export const FILLER_ID = 'SHD_257';

interface IIndexCard { internalName: string; name: string; setCode?: string; types: string[]; cost?: number; isToken?: boolean; isLeader?: boolean; unique?: boolean }

/** The sandbox card index the dev server serves (generated by scripts/sandbox/sync-engine-assets.mjs). */
export const readCardIndex = (): IIndexCard[] =>
    JSON.parse(fs.readFileSync(path.join(__dirname, '../../../public/sandbox/card-index.json'), 'utf8')).cards;

/** Card identity exactly as /sandbox builds it: the served card index plus the reprint set-code map (generated assets). */
export const realReplayCards = (): IReplayCards => {
    const root = path.join(__dirname, '../../../public/sandbox');
    const all = JSON.parse(fs.readFileSync(path.join(root, 'card-index.json'), 'utf8')).cards as ISandboxCard[];
    const by = new Map(all.map((c) => [c.internalName, c]));
    const setCodesFile = path.join(root, 'engine/set-codes.json');
    const setCodes = fs.existsSync(setCodesFile) ? JSON.parse(fs.readFileSync(setCodesFile, 'utf8')) as Record<string, string> : null;
    return replayCardsFrom({ all, get: (n) => by.get(n) }, setCodes);
};

/** `n` distinct non-unique units (by set code) to pad synthetic decks with, so draws name real, varied cards. */
export const varietyFiller = (n: number, avoid: Set<string>): string[] =>
    readCardIndex()
        .filter((c) => c.setCode && c.types.includes('unit') && !c.isToken && !c.isLeader && !c.unique && (c.cost ?? 9) <= 5 && !avoid.has(c.setCode))
        .map((c) => c.setCode!)
        .sort()
        .filter((_, i) => i % 7 === 0)
        .slice(0, n);

/**
 * A TEST decklist per seat that is consistent with the replay (we never have the real ones): every card the
 * seat's own recording ever shows, at the most copies seen at one moment (fortifications included), plus
 * Underworld Thug filler up to the starting deck size. SWUDB/SWU Forge deck JSON.
 */
export const syntheticDecklists = (game: IReplayGame, fillerIds: string[] = [FILLER_ID]): Record<'p1' | 'p2', string> => {
    const out = {} as Record<'p1' | 'p2', string>;
    for (const seat of ['p1', 'p2'] as const) {
        const rec = seat === 'p1' ? game.a : game.b;
        const pid = game.seats[seat].playerId;
        const max: Record<string, number> = {};
        rec.frames.forEach((frame, i) => {
            const p = frame.gamestate.players[pid];
            const count: Record<string, number> = {};
            const add = (c: NormalizedCard | null | undefined) => {
                if (c?.cardId && !/^token/i.test(c.type ?? '') && c.uuid !== p.leader?.uuid) {
                    count[c.cardId] = (count[c.cardId] ?? 0) + 1;
                }
            };
            for (const pile of ['hand', 'resources', 'discard', 'groundArena', 'spaceArena'] as const) {
                p.cardPiles[pile].forEach(add);
            }
            (p.base?.upgrades ?? game.fortifications[seat]?.[i] ?? []).forEach(add);
            for (const [id, n] of Object.entries(count)) {
                max[id] = Math.max(max[id] ?? 0, n);
            }
        });
        const deck = Object.entries(max).map(([id, count]) => ({ id, count }));
        let missing = game.seats[seat].startingDeckCount - deck.reduce((s, e) => s + e.count, 0);
        // pad with up to 3 copies of each filler card, round robin, then Underworld Thug
        const pad: Record<string, number> = {};
        for (let round = 0; round < 3 && missing > 0; round++) {
            for (const id of fillerIds) {
                if (missing > 0 && !max[id]) {
                    pad[id] = (pad[id] ?? 0) + 1;
                    missing--;
                }
            }
        }
        if (missing > 0) {
            pad[FILLER_ID] = (pad[FILLER_ID] ?? 0) + missing;
        }
        out[seat] = JSON.stringify({
            metadata: { name: `Synthetic ${seat.toUpperCase()} test deck`, author: 'test' },
            leader: { id: game.seats[seat].leaderCardId, count: 1 },
            base: { id: game.seats[seat].baseCardId, count: 1 },
            deck: [...deck, ...Object.entries(pad).map(([id, count]) => ({ id, count }))],
            sideboard: [],
        });
    }
    return out;
};
